Statistics
3e54Ni7HTXo3Ds/java-explore-with-me pull request #1
Opened 2023-02-01 18:30 UTC by 3e54Ni7HTXo3Ds

2023-02-05 21:25 UTC, alexache requested changes

2023-02-05 21:25 UTC, alexache commented on stats/stats-client/src/main/java/ru/practicum/ewm/stats/client/BaseClient.java
> +public class BaseClient {
Немного недопонял, это и есть клиент сервера статистики? А где метод отправки/полкчения статистики?

2023-02-06 19:23 UTC, 3e54Ni7HTXo3Ds commented on stats/stats-client/src/main/java/ru/practicum/ewm/stats/client/BaseClient.java
> +public class BaseClient {
Добавил statsclient

2023-02-06 22:43 UTC, alexache approved these changes

2023-02-06 22:43 UTC, alexache commented on stats/stats-client/src/main/java/ru/practicum/ewm/stats/client/StatsClient.java
> +    public ResponseEntity<Object> createHit(HttpServletRequest httpServletRequest) {
Это можно бы и void сделать

2023-02-06 22:43 UTC, alexache commented on stats/stats-client/src/main/java/ru/practicum/ewm/stats/client/StatsClient.java
> +    public ResponseEntity<Object> getHits(String start, String end, String uris, Boolean unique) {
С Object в будущем будет, пожалуй, неудобно. Лучше бы срвзу предусматривать возвращение списка ДТО объектов с полноценной десериалзацией

2023-02-07 20:02 UTC, 3e54Ni7HTXo3Ds commented on stats/stats-client/src/main/java/ru/practicum/ewm/stats/client/StatsClient.java
> +    public ResponseEntity<Object> createHit(HttpServletRequest httpServletRequest) {
Ок

2023-02-19 20:08 UTC, merged