Main svc
3e54Ni7HTXo3Ds/java-explore-with-me pull request #3
Opened 2023-02-14 01:03 UTC by 3e54Ni7HTXo3Ds

2023-02-14 23:29 UTC, alexache requested changes

2023-02-14 23:29 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/compilation/CompilationServiceImpl.java
> +                compilationRepository.findById(id).orElseThrow(new NotFoundParameterException("Wrong compilation"));
https://stackoverflow.com/a/70118020 ответит на вопрос почему лучше писать orElseThrow(() -> new NotFoundParameterException())

2023-02-14 23:29 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +        if (rangeStart != null) startTime = LocalDateTime.parse(rangeStart, dateTimeFormatter);
Не очень читаемый набор условий - будет лучше следовать стайл гайду и сделать отступы, фигурные скобки

2023-02-14 23:29 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/event/model/Event.java
> +    private Long eventConfirmedRequests;//
Это не должно храниться в базе, потому что можно получать из таблицы запросов на участие

2023-02-14 23:29 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/event/model/Event.java
> +    private Long eventViews;//
Это не должно храниться  в базе, а должно брать из сервиса статистики

2023-02-14 23:29 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/event/controller/PublicEventController.java
> +        List<HitResponseDto> hits = statsClient.getHits(null, null, request.getRequestURI(), false).getBody();
Довольно странный запрос статистики - без использования айди событий

2023-02-14 23:29 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +                confirmed++;
Это очень плохой способ, нужно считать это через запрос к базе

2023-02-14 23:29 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +        event.setEventConfirmedRequests(confirmed);
Это вот тоже неправильное - не нужно их хранить в базе

2023-02-15 13:20 UTC, 3e54Ni7HTXo3Ds commented on main-service/src/main/java/ru/practicum/ewm/compilation/CompilationServiceImpl.java
> +                compilationRepository.findById(id).orElseThrow(new NotFoundParameterException("Wrong compilation"));
ок

2023-02-15 13:26 UTC, 3e54Ni7HTXo3Ds commented on main-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +        if (rangeStart != null) startTime = LocalDateTime.parse(rangeStart, dateTimeFormatter);
ок

2023-02-15 20:25 UTC, 3e54Ni7HTXo3Ds commented on main-service/src/main/java/ru/practicum/ewm/event/model/Event.java
> +    private Long eventConfirmedRequests;//
ок

2023-02-15 20:26 UTC, 3e54Ni7HTXo3Ds commented on main-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +                confirmed++;
ок

2023-02-15 20:26 UTC, 3e54Ni7HTXo3Ds commented on main-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +        event.setEventConfirmedRequests(confirmed);
ок

2023-02-16 01:38 UTC, 3e54Ni7HTXo3Ds commented on main-service/src/main/java/ru/practicum/ewm/event/model/Event.java
> +    private Long eventViews;//
ок

2023-02-16 01:38 UTC, 3e54Ni7HTXo3Ds commented on main-service/src/main/java/ru/practicum/ewm/event/controller/PublicEventController.java
> +        List<HitResponseDto> hits = statsClient.getHits(null, null, request.getRequestURI(), false).getBody();
ок

2023-02-16 23:49 UTC, alexache requested changes

2023-02-16 23:49 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/user/UserServiceImpl.java
> +        User user = new User(null, userRequestDto.getName(), userRequestDto.getEmail());
а почему не через маппер?

2023-02-16 23:49 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +                statsClient.getHits(null, null, httpServletRequest.getRequestURI(), false).getBody();
А что здесь за URI в случае запроса всех событий? А ведь нужно идти по URI от ивентов, которые в списке

2023-02-16 23:49 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +                    eventConfirmedRequests++;
Можно делать серез стримы, мап и groupingBy

2023-02-16 23:49 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +                    if (dto.getUri().equals(httpServletRequest.getRequestURI())) {
Это вот вряд ли работает с получением списка событий

2023-02-16 23:49 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +        setConfirmedRequestsAndViews(list, httpServletRequest);
А где сортировка по количеству просмотров?

2023-02-17 11:28 UTC, 3e54Ni7HTXo3Ds commented on main-service/src/main/java/ru/practicum/ewm/user/UserServiceImpl.java
> +        User user = new User(null, userRequestDto.getName(), userRequestDto.getEmail());
Ок

2023-02-18 09:25 UTC, 3e54Ni7HTXo3Ds commented on main-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +        setConfirmedRequestsAndViews(list, httpServletRequest);
ок

2023-02-18 09:25 UTC, 3e54Ni7HTXo3Ds commented on main-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +                    if (dto.getUri().equals(httpServletRequest.getRequestURI())) {
ок

2023-02-18 09:26 UTC, 3e54Ni7HTXo3Ds commented on main-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +                statsClient.getHits(null, null, httpServletRequest.getRequestURI(), false).getBody();
ок

2023-02-18 12:40 UTC, 3e54Ni7HTXo3Ds commented on main-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +                    eventConfirmedRequests++;
ок

2023-02-19 19:54 UTC, alexache approved these changes

2023-02-19 20:05 UTC, merged